services:
  web:
    build: .
    container_name: nour_apache
    ports:
      - "8080:80"  # web server - change via GUI Settings
    volumes:
      - ./www:/var/www/html 
      - ./config/php/php.ini:/usr/local/etc/php/php.ini:ro
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=nour_db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=041201
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - nour_network

  db:
    image: mysql:8.0
    container_name: nour_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 041201
      MYSQL_DATABASE: nour_db
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: unless-stopped
    networks:
      - nour_network
    
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: nour_pma
    ports:
      - "8081:80"  # pma - change via GUI Settings
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 041201
      UPLOAD_LIMIT: 64M
      PMA_ARBITRARY: 1
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - nour_network

networks:
  nour_network:
    driver: bridge